### ISSUE TITLE
First block with InnerBlock is not refreshing on field change

### ISSUE THREAD

**Issue by phmasek** [AdvancedCustomFields/acf#452]
## To recreate:
1. Register new block type that supports `jsx`
2. Create field group for the new block type and add any field
3. Create the render template for the new block type and add the code below
4. Add the new block into a page twice
5. Change the value of the field in the block type for both blocks on the page. You will see that the first block does not trigger the refresh, whereas the second one works.

#### Add to `function.php`
```php
<?php
add_action('acf/init', 'anything_acf_debug_block_init');
function anything_acf_debug_block_init()
{
    // check function exists
    if (function_exists('acf_register_block')) {
        // register blocks
        acf_register_block(array(
            'name'            => 'debug',
            'title'           => __('Debug block..'),
            'description'     => __('Description.'),
            'render_template' => 'template-parts/blocks/debug-block.php',
            'category'        => 'formatting',
            'mode'            => 'preview',
            'icon'            => 'admin-users',
            'keywords'        => array(),
            'supports'        => array(
                'align'  => false,
                'anchor' => true,
                'jsx'    => true
            )
        ));
    }
}
```

#### `template-parts/blocks/debug-block.php`
```php
<?php var_dump(get_field('the_added_field')); ?>
<div>
  <InnerBlocks
        allowedBlocks="<?php echo esc_attr(wp_json_encode(['core/heading', 'core/paragraph'])); ?>"
        template="<?php echo esc_attr(wp_json_encode([['core/heading', ['placeholder' => 'Add header']], ['core/paragraph', ['placeholder' => 'Add paragraph']]])); ?>"
        templateLock="all"
    />
</div>
```

## Expected behaviour
The block shall respond normally no matter in what sequence it is added.

## Versions
Wordpress: `5.6`
ACF Pro: `5.9.4`

**Comment by elliotcondon** [comment]
@phmasek Thanks for the bug report and thorough instructions 🙌.

I've just spent some time investigating this issue, but was unable to replicate any problem - please see screen-cast showing the blocks working correctly as expected (disregard the validation error message at end of video 😓).
https://www.loom.com/share/533286218a1f44bfb6deb8f9c64f9605

**Comment by phmasek** [comment]
@elliotcondon that is very strange. Here's a video of how it behaves on my side.
It seems that it doesn't properly set the event listener for the field. Where is this set and how? Do you have any suggestions of what more I could do?

https://www.loom.com/share/b5a421efebf549fc96cce2791f92cbd4

**Comment by elliotcondon** [comment]
Thanks @phmasek. Can this issue be replicated on a Vanilla WordPress install? 
- Perhaps the issue only surfaces with another plugin or theme active?
- 
We haven't received any widespread reports of the issue, so I suspect there will be something unique about your site that is playing some role in the issue.

**Comment by phmasek** [comment]
@elliotcondon I have no other plugins installed and when I bypass all theme specific resources I still experience the same issue.

I tried a vanilla install using the Wordpress docker instance `wordpress:php7.4-apache` to make sure my environment is not causing any conflict, but I am still experiencing the same thing...

I unminified the `acf-pro-blocks.min.js` and found that `this.subscribed=false` when calling `setState` for the form element in the sidepanel. Why do you think that is?

It calls 1) `fetch` and 2) `setHtml` perfectly.

**Comment by elliotcondon** [comment]
Hi @phmasek 

At this stage, if we are both experiencing different results on Vanilla installations, we should setup a staging site online where we can both login and replicate the issue. Is there any chance you could spin up a site and share login details with me?

**Comment by phmasek** [comment]
Here you go. 

1. Activate the `twentytwenty` theme
2. Activate `acf` plugin
3. Add new page
4. Add debug block in editor


```yml
version: "3.9"
services:
  web:
    image: melker/acf-bug:latest
    restart: always
    privileged: true
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pw
      WORDPRESS_DB_NAME: wp_db
    ports:
      - 8088:80
    networks:
      - backend

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pw
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql

networks:
  backend:

volumes:
  db:

```
