### ISSUE TITLE
More sensible styles for .acf-hidden

### ISSUE THREAD

**Issue by hirasso** [AdvancedCustomFields/acf#503]
Hi there,

I am using [ACF Autosize](https://github.com/yeah8000/acf-autosize) on many of my sites. It works great to make the UX more slick! One problem I encountered, though, is that if an `.acf-field` has the class `.acf-hidden` due to ACF tabs or conditional logic, the autosize plugin can't work it's magic, due to the fact that `display: none !important` is applied to the `.acf-hidden` field (= no height!).

I came up with this overwrite, which solves this problem by hiding the element visually, but still allowing the height of the `wysiwyg` or `textarea` to be adjusted correctly:
```css
.acf-hidden {
  /* I only needed this to overwrite ACF's default style for .acf-hidden: */
  display: block !important; 
  /* Take the element out of the stacking context: */
  position: fixed !important; 
  /* Move the element out of the viewport: */ 
  left: -100000px !important;
}
/* Remove tab focus and pointer events from the acf-field and all it's children */
.acf-hidden,
.acf-hidden * {
  pointer-events: none !important;
  visibility: hidden !important;
}
```
Maybe this could be included in ACF core?
