### ISSUE TITLE
Not enough space for editing sub fields inside nested repeaters ACF 6.0.1

### ISSUE THREAD

**Issue by xxvii** [AdvancedCustomFields/acf#722]
Hello,
I have some nested repeaters inside flexible content fields and a lot of space is wasted for the editing of sub fields.
As you can see, with only two nested repeaters the space in the last one is not enough to work comfortably.

Consider removing or reviewing the rule

```css
.acf-admin-single-field-group .acf-field-object-flexible-content .acf-is-subfields .acf-field-object .acf-label, 
.acf-admin-single-field-group .acf-field-object-flexible-content .acf-is-subfields .acf-field-object .acf-input {
  max-width: 600px;
}
```
inside /advanced-custom-fields-pro/assets/build/css/acf-field-group.css

![Modifica-gruppo-di-campi-“Contenuti”-‹-Cordivari-—-WordPress](https://user-images.githubusercontent.com/962750/192976271-278f6308-62a3-45da-978f-a9fa45bfbac9.png)
