### ISSUE TITLE
Field groups in editor sidebar looks very different to the native style

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#753]
Hey @lgladdy @polevaultweb,

like you can see in the screenshot, the ACF field groups toggle area located in editor sidebar looks very different to the native style:

<img width="349" alt="Bildschirmfoto 2022-11-10 um 21 25 04" src="https://user-images.githubusercontent.com/31563167/201198642-5736b4ea-2539-4b42-b73c-cade723a00dc.png">

Here is the CSS code I use to get exactly the same result like the native accordions:

```css
/******************************************************/
/* ACF - FIX WRONG STYLE OF TOGGLE AREAS IN EDITOR SIDEBAR */
/******************************************************/

#side-sortables .acf-postbox .postbox-header {
	position: relative!important;
}

#side-sortables .acf-postbox:first-child .postbox-header {
	border-top: 0!important;
}

#side-sortables .acf-postbox h2.hndle {
    padding: 0 16px!important;
	font-size: 13px!important;
	font-weight: 500!important;
}

#side-sortables .acf-postbox .acf-hndle-cog,
#side-sortables .acf-postbox .order-higher-indicator,
#side-sortables .acf-postbox .order-lower-indicator {
	display: none!important;
}

#side-sortables .acf-postbox .toggle-indicator {
    position: absolute;
    right: 16px;
    top: 50%;
	width: 24px;
	height: 24px;
    transform: translateY(-50%);
    transition: color .1s ease-in-out;
}

#side-sortables .acf-postbox .handlediv {
	box-shadow: none!important;
}

#side-sortables .acf-postbox .handlediv .toggle-indicator:before {
	content: ''!important;
	width: 100%;
	height: 100%;
	background: url('data:image/svg+xml;charset=UTF-8,<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" class="components-panel__arrow" aria-hidden="true" focusable="false"><path d="M17.5 11.6L12 16l-5.5-4.4.9-1.2L12 14l4.5-3.6 1 1.2z"></path></svg>');
	background-repeat: no-repeat;
	background-position: center;
}

#side-sortables .acf-postbox .handlediv[aria-expanded="true"] .toggle-indicator:before {
	background: url('data:image/svg+xml;charset=UTF-8,<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" class="components-panel__arrow" aria-hidden="true" focusable="false"><path d="M6.5 12.4L12 8l5.5 4.4-.9 1.2L12 10l-4.5 3.6-1-1.2z"></path></svg>');
}
```
